alter table if exists "index" drop constraint if exists FK_index_lemma;
alter table if exists lemma drop constraint if exists FK_lemma_site;
alter table if exists "index" drop constraint if exists FK_index_page;
alter table if exists page drop constraint if exists FK_page_site;
alter table if exists site drop constraint if exists FK_site_type;

drop table if exists field cascade;
drop table if exists "index" cascade;
drop table if exists lemma cascade;
drop table if exists page cascade;
drop table if exists site cascade;
drop table if exists type cascade;

create table field (
    id int4 generated by default as identity,
    name varchar(255) not null,
    selector varchar(255) not null,
    weight float4 not null,
    primary key (id)
);

create table "index" (
    id int4 generated by default as identity,
    "rank" float4 not null,
    lemma_id int4 not null,
    page_id int4 not null,
    primary key (id)
);

create table lemma (
    id int4 generated by default as identity,
    frequency float4 not null,
    lemma varchar(255) not null,
    site_id int4 not null,
    primary key (id)
);

create table page (
    id int4 generated by default as identity,
    code int4 not null,
    content text not null,
    path text not null,
    site_id int4 not null,
    primary key (id)
);

create table site (
    id int4 generated by default as identity,
    last_error text,
    name text not null,
    status_time timestamp not null,
    type varchar(8) not null,
    url text not null,
    primary key (id)
);

create table type (
    id varchar(8),
    primary key (id)
);

create index IX_lemma_lemma on lemma (lemma);
create index IX_page_path on page (path);
create index IX_index_lemma on "index" (lemma_id);
create index IX_index_page on "index" (page_id);
create index IX_lemma_site on lemma (site_id);
create index IX_page_site on page (site_id);

alter table if exists "index" add constraint FK_index_lemma foreign key (lemma_id) references lemma on delete cascade;
alter table if exists "index" add constraint FK_index_page foreign key (page_id) references page on delete cascade;
alter table if exists lemma add constraint FK_lemma_site foreign key (site_id) references site on delete cascade;
alter table if exists page add constraint FK_page_site foreign key (site_id) references site on delete cascade;
alter table if exists site add constraint FK_site_type foreign key (type) references type on delete cascade;
